*&---------------------------------------------------------------------*
*& Include          ZMINESWEEPER_SCR
*&---------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF BLOCK BL0 WITH FRAME TITLE TEXT-T00.
  SELECTION-SCREEN BEGIN OF BLOCK BL2 WITH FRAME TITLE TEXT-T02.
    PARAMETERS: easy   RADIOBUTTON GROUP gr2 DEFAULT 'X' USER-COMMAND GR2,
                normal RADIOBUTTON GROUP gr2,
                hard   RADIOBUTTON GROUP gr2,
                vhard  RADIOBUTTON GROUP gr2,
                own    RADIOBUTTON GROUP gr2.
    SELECTION-SCREEN BEGIN OF BLOCK BL3 WITH FRAME TITLE TEXT-T03.
      PARAMETERS: p_x TYPE i DEFAULT '20' MODIF ID OWN,
                  p_y TYPE i DEFAULT '20' MODIF ID OWN,
                  p_m TYPE i DEFAULT '30' MODIF ID OWN.
    SELECTION-SCREEN END OF BLOCK BL3.
  SELECTION-SCREEN END OF BLOCK BL2.
  SELECTION-SCREEN BEGIN OF BLOCK BL1 WITH FRAME TITLE TEXT-T01.
    PARAMETERS: p_m_n  RADIOBUTTON GROUP gr1,
                p_vn_n RADIOBUTTON GROUP gr1 DEFAULT 'X'.
    SELECTION-SCREEN SKIP.
    SELECTION-SCREEN SKIP.
    SELECTION-SCREEN SKIP.
    SELECTION-SCREEN SKIP.
    SELECTION-SCREEN SKIP.
    SELECTION-SCREEN SKIP.
    SELECTION-SCREEN SKIP.
  SELECTION-SCREEN END OF BLOCK BL1.
SELECTION-SCREEN END OF BLOCK BL0.

SELECTION-SCREEN BEGIN OF SCREEN 0002 AS SUBSCREEN.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(50) cmine.
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(50) cflag.
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(50) ccflag.
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(50) ciflag.
  SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF SCREEN 0002.
